favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5393661467824131
  brandStrength: 0.9039405859075487
  rhythmicContrast: 0.8070627045817673
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  lightness: 0.7902559419162571
typography_spectrum: 0.853644
layout_spectrum: 0.6409796
analytics:
  twitter: null
  google: null
  facebook: null
name: BillandMendi
